# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_bulk_update_request_v2_payload import ProductBulkUpdateRequestV2Payload

class TestProductBulkUpdateRequestV2Payload(unittest.TestCase):
    """ProductBulkUpdateRequestV2Payload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductBulkUpdateRequestV2Payload:
        """Test ProductBulkUpdateRequestV2Payload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductBulkUpdateRequestV2Payload`
        """
        model = ProductBulkUpdateRequestV2Payload()
        if include_optional:
            return ProductBulkUpdateRequestV2Payload(
                update_mask = product.models.product_field_mask.productFieldMask(
                    paths = [
                        ''
                        ], ),
                attributes = {
                    'key' : {
                        'key' : None
                        }
                    }
            )
        else:
            return ProductBulkUpdateRequestV2Payload(
        )
        """

    def testProductBulkUpdateRequestV2Payload(self):
        """Test ProductBulkUpdateRequestV2Payload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
