# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_bulk_update_request_payload import ProductBulkUpdateRequestPayload

class TestProductBulkUpdateRequestPayload(unittest.TestCase):
    """ProductBulkUpdateRequestPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductBulkUpdateRequestPayload:
        """Test ProductBulkUpdateRequestPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductBulkUpdateRequestPayload`
        """
        model = ProductBulkUpdateRequestPayload()
        if include_optional:
            return ProductBulkUpdateRequestPayload(
                update_mask = product.models.product_field_mask.productFieldMask(
                    paths = [
                        ''
                        ], ),
                attributes = {
                    'key' : {
                        'key' : None
                        }
                    }
            )
        else:
            return ProductBulkUpdateRequestPayload(
        )
        """

    def testProductBulkUpdateRequestPayload(self):
        """Test ProductBulkUpdateRequestPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
