# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.entitymanager_update_attribute_options_request import EntitymanagerUpdateAttributeOptionsRequest

class TestEntitymanagerUpdateAttributeOptionsRequest(unittest.TestCase):
    """EntitymanagerUpdateAttributeOptionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitymanagerUpdateAttributeOptionsRequest:
        """Test EntitymanagerUpdateAttributeOptionsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitymanagerUpdateAttributeOptionsRequest`
        """
        model = EntitymanagerUpdateAttributeOptionsRequest()
        if include_optional:
            return EntitymanagerUpdateAttributeOptionsRequest(
                tenant_id = '',
                list_code = '',
                options = [
                    product.models.entitymanager_attribute_option.entitymanagerAttributeOption(
                        option = {
                            'key' : ''
                            }, 
                        sort = 56, 
                        id = '', 
                        code = '', 
                        value = product.models.productentitymanager_localized_text.productentitymanagerLocalizedText(), 
                        swatches = [
                            product.models.entitymanager_attribute_option_swatch.entitymanagerAttributeOptionSwatch(
                                grn = '', 
                                hex = '', )
                            ], )
                    ]
            )
        else:
            return EntitymanagerUpdateAttributeOptionsRequest(
        )
        """

    def testEntitymanagerUpdateAttributeOptionsRequest(self):
        """Test EntitymanagerUpdateAttributeOptionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
