# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_bulk_delete_products_request import ProductBulkDeleteProductsRequest

class TestProductBulkDeleteProductsRequest(unittest.TestCase):
    """ProductBulkDeleteProductsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductBulkDeleteProductsRequest:
        """Test ProductBulkDeleteProductsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductBulkDeleteProductsRequest`
        """
        model = ProductBulkDeleteProductsRequest()
        if include_optional:
            return ProductBulkDeleteProductsRequest(
                tenant_id = '',
                ids = [
                    ''
                    ]
            )
        else:
            return ProductBulkDeleteProductsRequest(
        )
        """

    def testProductBulkDeleteProductsRequest(self):
        """Test ProductBulkDeleteProductsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
