# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.entitymanager_types import EntitymanagerTypes

class TestEntitymanagerTypes(unittest.TestCase):
    """EntitymanagerTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntitymanagerTypes(self):
        """Test EntitymanagerTypes"""
        # inst = EntitymanagerTypes()

if __name__ == '__main__':
    unittest.main()
