# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.entitymanager_create_attribute_options_response import EntitymanagerCreateAttributeOptionsResponse

class TestEntitymanagerCreateAttributeOptionsResponse(unittest.TestCase):
    """EntitymanagerCreateAttributeOptionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitymanagerCreateAttributeOptionsResponse:
        """Test EntitymanagerCreateAttributeOptionsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitymanagerCreateAttributeOptionsResponse`
        """
        model = EntitymanagerCreateAttributeOptionsResponse()
        if include_optional:
            return EntitymanagerCreateAttributeOptionsResponse(
                options = [
                    product.models.entitymanager_attribute_option.entitymanagerAttributeOption(
                        option = {
                            'key' : ''
                            }, 
                        sort = 56, 
                        id = '', 
                        code = '', 
                        value = product.models.productentitymanager_localized_text.productentitymanagerLocalizedText(), 
                        swatches = [
                            product.models.entitymanager_attribute_option_swatch.entitymanagerAttributeOptionSwatch(
                                grn = '', 
                                hex = '', )
                            ], )
                    ],
                errors = [
                    product.models.entitymanager_attribute_option_errors.entitymanagerAttributeOptionErrors(
                        error = '', 
                        option = {
                            'key' : ''
                            }, )
                    ]
            )
        else:
            return EntitymanagerCreateAttributeOptionsResponse(
        )
        """

    def testEntitymanagerCreateAttributeOptionsResponse(self):
        """Test EntitymanagerCreateAttributeOptionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
