# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_list_variants_by_sku_request import ProductListVariantsBySkuRequest

class TestProductListVariantsBySkuRequest(unittest.TestCase):
    """ProductListVariantsBySkuRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductListVariantsBySkuRequest:
        """Test ProductListVariantsBySkuRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductListVariantsBySkuRequest`
        """
        model = ProductListVariantsBySkuRequest()
        if include_optional:
            return ProductListVariantsBySkuRequest(
                tenant_id = '',
                sku = ''
            )
        else:
            return ProductListVariantsBySkuRequest(
        )
        """

    def testProductListVariantsBySkuRequest(self):
        """Test ProductListVariantsBySkuRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
