# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_assets_entry_metadata import ProductAssetsEntryMetadata

class TestProductAssetsEntryMetadata(unittest.TestCase):
    """ProductAssetsEntryMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductAssetsEntryMetadata:
        """Test ProductAssetsEntryMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductAssetsEntryMetadata`
        """
        model = ProductAssetsEntryMetadata()
        if include_optional:
            return ProductAssetsEntryMetadata(
                roles = [
                    ''
                    ],
                alt = product.models.product_localized_text.productLocalizedText(
                    value = {
                        'key' : ''
                        }, )
            )
        else:
            return ProductAssetsEntryMetadata(
        )
        """

    def testProductAssetsEntryMetadata(self):
        """Test ProductAssetsEntryMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
