# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.entitymanager_list_entities_request import EntitymanagerListEntitiesRequest

class TestEntitymanagerListEntitiesRequest(unittest.TestCase):
    """EntitymanagerListEntitiesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitymanagerListEntitiesRequest:
        """Test EntitymanagerListEntitiesRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitymanagerListEntitiesRequest`
        """
        model = EntitymanagerListEntitiesRequest()
        if include_optional:
            return EntitymanagerListEntitiesRequest(
                tenant_id = '',
                page_size = 56
            )
        else:
            return EntitymanagerListEntitiesRequest(
        )
        """

    def testEntitymanagerListEntitiesRequest(self):
        """Test EntitymanagerListEntitiesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
