# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_bulk_update_response_response import ProductBulkUpdateResponseResponse

class TestProductBulkUpdateResponseResponse(unittest.TestCase):
    """ProductBulkUpdateResponseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductBulkUpdateResponseResponse:
        """Test ProductBulkUpdateResponseResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductBulkUpdateResponseResponse`
        """
        model = ProductBulkUpdateResponseResponse()
        if include_optional:
            return ProductBulkUpdateResponseResponse(
                product_id = '',
                success = True,
                attributes = {
                    'key' : {
                        'key' : None
                        }
                    }
            )
        else:
            return ProductBulkUpdateResponseResponse(
        )
        """

    def testProductBulkUpdateResponseResponse(self):
        """Test ProductBulkUpdateResponseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
