# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_list_variants_by_sku_response import ProductListVariantsBySkuResponse

class TestProductListVariantsBySkuResponse(unittest.TestCase):
    """ProductListVariantsBySkuResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductListVariantsBySkuResponse:
        """Test ProductListVariantsBySkuResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductListVariantsBySkuResponse`
        """
        model = ProductListVariantsBySkuResponse()
        if include_optional:
            return ProductListVariantsBySkuResponse(
                variants = [
                    product.models.product_product_variant.productProductVariant(
                        id = '', 
                        grn = '', 
                        max_saleable_quantity = 56, 
                        attributes = {
                            'key' : {
                                'key' : None
                                }
                            }, )
                    ]
            )
        else:
            return ProductListVariantsBySkuResponse(
        )
        """

    def testProductListVariantsBySkuResponse(self):
        """Test ProductListVariantsBySkuResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
