# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.entitymanager_render_as import EntitymanagerRenderAs

class TestEntitymanagerRenderAs(unittest.TestCase):
    """EntitymanagerRenderAs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntitymanagerRenderAs(self):
        """Test EntitymanagerRenderAs"""
        # inst = EntitymanagerRenderAs()

if __name__ == '__main__':
    unittest.main()
