# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_localized_text import ProductLocalizedText

class TestProductLocalizedText(unittest.TestCase):
    """ProductLocalizedText unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductLocalizedText:
        """Test ProductLocalizedText
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductLocalizedText`
        """
        model = ProductLocalizedText()
        if include_optional:
            return ProductLocalizedText(
                value = {
                    'key' : ''
                    }
            )
        else:
            return ProductLocalizedText(
        )
        """

    def testProductLocalizedText(self):
        """Test ProductLocalizedText"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
