# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.entitymanager_list_options_lists_response import EntitymanagerListOptionsListsResponse

class TestEntitymanagerListOptionsListsResponse(unittest.TestCase):
    """EntitymanagerListOptionsListsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitymanagerListOptionsListsResponse:
        """Test EntitymanagerListOptionsListsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitymanagerListOptionsListsResponse`
        """
        model = EntitymanagerListOptionsListsResponse()
        if include_optional:
            return EntitymanagerListOptionsListsResponse(
                options = [
                    product.models.entitymanager_options_list.entitymanagerOptionsList(
                        code = '', 
                        name = '', )
                    ]
            )
        else:
            return EntitymanagerListOptionsListsResponse(
        )
        """

    def testEntitymanagerListOptionsListsResponse(self):
        """Test EntitymanagerListOptionsListsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
