# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.entitymanager_update_attribute_group_request import EntitymanagerUpdateAttributeGroupRequest

class TestEntitymanagerUpdateAttributeGroupRequest(unittest.TestCase):
    """EntitymanagerUpdateAttributeGroupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitymanagerUpdateAttributeGroupRequest:
        """Test EntitymanagerUpdateAttributeGroupRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitymanagerUpdateAttributeGroupRequest`
        """
        model = EntitymanagerUpdateAttributeGroupRequest()
        if include_optional:
            return EntitymanagerUpdateAttributeGroupRequest(
                tenant_id = '',
                code = '',
                payload = product.models.entitymanager_update_attribute_group_request_payload.entitymanagerUpdateAttributeGroupRequestPayload(
                    label = product.models.productentitymanager_localized_text.productentitymanagerLocalizedText(
                        value = {
                            'key' : ''
                            }, ), 
                    sort = 56, 
                    visibility = [
                        ''
                        ], ),
                field_mask = ''
            )
        else:
            return EntitymanagerUpdateAttributeGroupRequest(
        )
        """

    def testEntitymanagerUpdateAttributeGroupRequest(self):
        """Test EntitymanagerUpdateAttributeGroupRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
