# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.entitymanager_get_attribute_options_request import EntitymanagerGetAttributeOptionsRequest

class TestEntitymanagerGetAttributeOptionsRequest(unittest.TestCase):
    """EntitymanagerGetAttributeOptionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitymanagerGetAttributeOptionsRequest:
        """Test EntitymanagerGetAttributeOptionsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitymanagerGetAttributeOptionsRequest`
        """
        model = EntitymanagerGetAttributeOptionsRequest()
        if include_optional:
            return EntitymanagerGetAttributeOptionsRequest(
                tenant_id = '',
                option_ids = [
                    product.models.entitymanager_get_attribute_options_request_option.entitymanagerGetAttributeOptionsRequestOption(
                        list_code = '', 
                        option_id = '', )
                    ]
            )
        else:
            return EntitymanagerGetAttributeOptionsRequest(
        )
        """

    def testEntitymanagerGetAttributeOptionsRequest(self):
        """Test EntitymanagerGetAttributeOptionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
