# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product.models.product_update_product_request_v2 import ProductUpdateProductRequestV2

class TestProductUpdateProductRequestV2(unittest.TestCase):
    """ProductUpdateProductRequestV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductUpdateProductRequestV2:
        """Test ProductUpdateProductRequestV2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductUpdateProductRequestV2`
        """
        model = ProductUpdateProductRequestV2()
        if include_optional:
            return ProductUpdateProductRequestV2(
                tenant_id = '',
                id = '',
                code = '',
                attributes_mask = product.models.product_field_mask.productFieldMask(
                    paths = [
                        ''
                        ], ),
                url_key = product.models.product_localized_text.productLocalizedText(
                    value = {
                        'key' : ''
                        }, ),
                max_saleable_quantity = 56,
                attributes = {
                    'key' : {
                        'key' : None
                        }
                    },
                variants = {
                    'key' : product.models.product_product_variant.productProductVariant(
                        id = '', 
                        grn = '', 
                        max_saleable_quantity = 56, 
                        attributes = {
                            'key' : {
                                'key' : None
                                }
                            }, )
                    },
                media_variant_attributes = [
                    ''
                    ]
            )
        else:
            return ProductUpdateProductRequestV2(
        )
        """

    def testProductUpdateProductRequestV2(self):
        """Test ProductUpdateProductRequestV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
