# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class EntitymanagerTypes(str, Enum):
    """
    EntitymanagerTypes
    """

    """
    allowed enum values
    """
    TEXT = 'TEXT'
    NUMBER = 'NUMBER'
    BOOLEAN = 'BOOLEAN'
    DATETIME = 'DATETIME'
    EXTERNAL = 'EXTERNAL'
    EMBED = 'EMBED'
    FLOAT32 = 'FLOAT32'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntitymanagerTypes from a JSON string"""
        return cls(json.loads(json_str))


