# coding: utf-8

"""
    Product Service

    API for managing products

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from product.models.product_attribute_response_error import ProductAttributeResponseError
from product.models.product_product_response_error import ProductProductResponseError
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ProductCreateProductResponse(BaseModel):
    """
    ProductCreateProductResponse
    """ # noqa: E501
    success: Optional[StrictBool] = None
    id: Optional[StrictStr] = None
    product_errors: Optional[List[ProductProductResponseError]] = Field(default=None, alias="productErrors")
    attribute_errors: Optional[List[ProductAttributeResponseError]] = Field(default=None, alias="attributeErrors")
    __properties: ClassVar[List[str]] = ["success", "id", "productErrors", "attributeErrors"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProductCreateProductResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in product_errors (list)
        _items = []
        if self.product_errors:
            for _item in self.product_errors:
                if _item:
                    _items.append(_item.to_dict())
            _dict['productErrors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attribute_errors (list)
        _items = []
        if self.attribute_errors:
            for _item in self.attribute_errors:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attributeErrors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ProductCreateProductResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "id": obj.get("id"),
            "productErrors": [ProductProductResponseError.from_dict(_item) for _item in obj.get("productErrors")] if obj.get("productErrors") is not None else None,
            "attributeErrors": [ProductAttributeResponseError.from_dict(_item) for _item in obj.get("attributeErrors")] if obj.get("attributeErrors") is not None else None
        })
        return _obj


